image: docker:24.0.5
services:
  - docker:24.0.5-dind
variables:
  DOCKER_TLS_CERTDIR: ""
stages:
  - build
  - test
build_images:
  stage: build
  script:
    - docker compose build
test_startup:
  stage: test
  script:
    - docker compose up -d
    - sleep 30
    - docker ps
    - docker compose logs backend
    - docker compose down 